//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DbCommands&gt;
        ///    &lt;DbCreation&gt;
        ///        &lt;Text Message=&quot;Creating table &apos;FileSystems&apos;&quot;&gt;
        ///            &lt;![CDATA[CREATE TABLE &quot;FileSystems&quot; (
        ///	&quot;Id&quot;	UNIQUEIDENTIFIER NOT NULL,
        ///	&quot;DisplayName&quot;	NVARCHAR(1024) NOT NULL CHECK(length(trim(DisplayName)) = length(DisplayName) AND length(DisplayName)&gt;0) UNIQUE COLLATE NOCASE,
        ///	&quot;CaseSensitiveSearch&quot;	BIT NOT NULL DEFAULT 0,
        ///	&quot;ReadOnly&quot;	BIT NOT NULL DEFAULT 0,
        ///	&quot;MaxNameLength&quot;	INT NOT NULL CHECK(MaxNameLength&gt;=1) DEFAULT 255,
        ///	&quot;DefaultDriveType&quot;	TINYINT CHECK(DefaultDr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbCommands {
            get {
                return ResourceManager.GetString("DbCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestData&gt;
        ///  &lt;Row ErrorMessage=&quot;Display Name is required.&quot;&gt;
        ///    &lt;Argument /&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row ErrorMessage=&quot;Display Name is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row ErrorMessage=&quot;Display Name is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[ ]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row ErrorMessage=&quot;Display Name is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisplayName1024 {
            get {
                return ResourceManager.GetString("DisplayName1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestData&gt;
        ///  &lt;Row ErrorMessage=&quot;Name is required.&quot;&gt;
        ///    &lt;Argument /&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row ErrorMessage=&quot;Name is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row ErrorMessage=&quot;Name is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[ ]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row ErrorMessage=&quot;Name is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Name1024 {
            get {
                return ResourceManager.GetString("Name1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;TestData.xsd&quot;&gt;
        ///    &lt;FileSystem Id=&quot;{bedb396b-2212-4149-9cad-7e437c47314c}&quot; DisplayName=&quot;New Technology File System&quot; DefaultDriveType=&quot;Fixed&quot; CreatedOn=&quot;2004-08-19T14:51:06&quot; ModifiedOn=&quot;2004-08-19T14:51:06&quot;&gt;
        ///        &lt;SymbolicName Id=&quot;{74381ccb-d56d-444d-890f-3a8051bc18e6}&quot; Name=&quot;NTFS&quot; Priority=&quot;0&quot; CreatedOn=&quot;2021-05-21T21:29:59&quot; ModifiedOn=&quot;2021-05-21T21:29:59&quot; /&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestData&gt;
        ///  &lt;Row ErrorMessage=&quot;Volume Identifier is required.&quot;&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[urn:volume:id:8378-6B24]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[urn:volume:id:8378-6B24]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[urn:uuid:62a9f77e-9bfe-435c-a5f5-177b0f8ecd83]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[urn:uuid:62a9f77e-9bfe-435c-a5f5-177b0f8ecd83]]&gt;&lt;/Expected [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VolumeIdentifier1024 {
            get {
                return ResourceManager.GetString("VolumeIdentifier1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestData&gt;
        ///  &lt;Row&gt;
        ///    &lt;Argument /&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[ ]]&gt;&lt;/Argument&gt;
        ///    &lt;Expected&gt;&lt;![CDATA[]]&gt;&lt;/Expected&gt;
        ///  &lt;/Row&gt;
        ///  &lt;Row&gt;
        ///    &lt;Argument&gt;&lt;![CDATA[
        ///                                                                                                                               
        ///]]&gt;&lt;/Argument&gt;
        ///    &lt;Expec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VolumeName128 {
            get {
                return ResourceManager.GetString("VolumeName128", resourceCulture);
            }
        }
    }
}
