//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to access the volume..
        /// </summary>
        public static string Description_VolumeStatus_AccessError {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume is under corporate control / ownership..
        /// </summary>
        public static string Description_VolumeStatus_Controlled {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_Controlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume has been destroyed..
        /// </summary>
        public static string Description_VolumeStatus_Destroyed {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume is offline or unavailable..
        /// </summary>
        public static string Description_VolumeStatus_Offline {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership / control of volume has been relinquished to another entity..
        /// </summary>
        public static string Description_VolumeStatus_Relinquished {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_Relinquished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume is being tracked, but is not under corporate control / ownership..
        /// </summary>
        public static string Description_VolumeStatus_Uncontrolled {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_Uncontrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of the volume is uknown or unspecified..
        /// </summary>
        public static string Description_VolumeStatus_Unknown {
            get {
                return ResourceManager.GetString("Description_VolumeStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Errors.
        /// </summary>
        public static string DisplayName_AccessErrors {
            get {
                return ResourceManager.GetString("DisplayName_AccessErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Properties.
        /// </summary>
        public static string DisplayName_AudioProperties {
            get {
                return ResourceManager.GetString("DisplayName_AudioProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline Comparisons.
        /// </summary>
        public static string DisplayName_BaselineComparisons {
            get {
                return ResourceManager.GetString("DisplayName_BaselineComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-sensitive Search.
        /// </summary>
        public static string DisplayName_CaseSensitiveSearch {
            get {
                return ResourceManager.GetString("DisplayName_CaseSensitiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlative Comparisons.
        /// </summary>
        public static string DisplayName_CorrelativeComparisons {
            get {
                return ResourceManager.GetString("DisplayName_CorrelativeComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Configuration.
        /// </summary>
        public static string DisplayName_CrawlConfiguration {
            get {
                return ResourceManager.GetString("DisplayName_CrawlConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Operation Failed.
        /// </summary>
        public static string DisplayName_CrawlOperationFailed {
            get {
                return ResourceManager.GetString("DisplayName_CrawlOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string DisplayName_CreatedOn {
            get {
                return ResourceManager.GetString("DisplayName_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Drive Type.
        /// </summary>
        public static string DisplayName_DefaultDriveType {
            get {
                return ResourceManager.GetString("DisplayName_DefaultDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName_DisplayName {
            get {
                return ResourceManager.GetString("DisplayName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Properties.
        /// </summary>
        public static string DisplayName_DocumentProperties {
            get {
                return ResourceManager.GetString("DisplayName_DocumentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Type.
        /// </summary>
        public static string DisplayName_DriveType {
            get {
                return ResourceManager.GetString("DisplayName_DriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRM Properties.
        /// </summary>
        public static string DisplayName_DRMProperties {
            get {
                return ResourceManager.GetString("DisplayName_DRMProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        public static string DisplayName_ErrorCode {
            get {
                return ResourceManager.GetString("DisplayName_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        public static string DisplayName_FileSystem {
            get {
                return ResourceManager.GetString("DisplayName_FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Properties.
        /// </summary>
        public static string DisplayName_GPSProperties {
            get {
                return ResourceManager.GetString("DisplayName_GPSProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier.
        /// </summary>
        public static string DisplayName_Identifier {
            get {
                return ResourceManager.GetString("DisplayName_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Properties.
        /// </summary>
        public static string DisplayName_ImageProperties {
            get {
                return ResourceManager.GetString("DisplayName_ImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path Error.
        /// </summary>
        public static string DisplayName_InvalidPathError {
            get {
                return ResourceManager.GetString("DisplayName_InvalidPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Error.
        /// </summary>
        public static string DisplayName_IOError {
            get {
                return ResourceManager.GetString("DisplayName_IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Inactive.
        /// </summary>
        public static string DisplayName_IsInactive {
            get {
                return ResourceManager.GetString("DisplayName_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Synchronized On.
        /// </summary>
        public static string DisplayName_LastSynchronizedOn {
            get {
                return ResourceManager.GetString("DisplayName_LastSynchronizedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Name Length.
        /// </summary>
        public static string DisplayName_MaxNameLength {
            get {
                return ResourceManager.GetString("DisplayName_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Properties.
        /// </summary>
        public static string DisplayName_MediaProperties {
            get {
                return ResourceManager.GetString("DisplayName_MediaProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string DisplayName_ModifiedOn {
            get {
                return ResourceManager.GetString("DisplayName_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Properties.
        /// </summary>
        public static string DisplayName_MusicProperties {
            get {
                return ResourceManager.GetString("DisplayName_MusicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DisplayName_Name {
            get {
                return ResourceManager.GetString("DisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DisplayName_Notes {
            get {
                return ResourceManager.GetString("DisplayName_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Too Long Error.
        /// </summary>
        public static string DisplayName_PathTooLongError {
            get {
                return ResourceManager.GetString("DisplayName_PathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Properties.
        /// </summary>
        public static string DisplayName_PhotoProperties {
            get {
                return ResourceManager.GetString("DisplayName_PhotoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string DisplayName_Priority {
            get {
                return ResourceManager.GetString("DisplayName_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        public static string DisplayName_ReadOnly {
            get {
                return ResourceManager.GetString("DisplayName_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded TV Properties.
        /// </summary>
        public static string DisplayName_RecordedTVProperties {
            get {
                return ResourceManager.GetString("DisplayName_RecordedTVProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundancy Set.
        /// </summary>
        public static string DisplayName_RedundantSet {
            get {
                return ResourceManager.GetString("DisplayName_RedundantSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string DisplayName_RootDirectory {
            get {
                return ResourceManager.GetString("DisplayName_RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Exception.
        /// </summary>
        public static string DisplayName_SecurityException {
            get {
                return ResourceManager.GetString("DisplayName_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Properties.
        /// </summary>
        public static string DisplayName_SummaryProperties {
            get {
                return ResourceManager.GetString("DisplayName_SummaryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Names.
        /// </summary>
        public static string DisplayName_SymbolicNames {
            get {
                return ResourceManager.GetString("DisplayName_SymbolicNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access Error.
        /// </summary>
        public static string DisplayName_UnauthorizedAccessError {
            get {
                return ResourceManager.GetString("DisplayName_UnauthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string DisplayName_UnexpectedError {
            get {
                return ResourceManager.GetString("DisplayName_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote DB Identifier.
        /// </summary>
        public static string DisplayName_UpstreamId {
            get {
                return ResourceManager.GetString("DisplayName_UpstreamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Properties.
        /// </summary>
        public static string DisplayName_VideoProperties {
            get {
                return ResourceManager.GetString("DisplayName_VideoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name.
        /// </summary>
        public static string DisplayName_VolumeName {
            get {
                return ResourceManager.GetString("DisplayName_VolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        public static string DisplayName_Volumes {
            get {
                return ResourceManager.GetString("DisplayName_Volumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Status.
        /// </summary>
        public static string DisplayName_VolumeStatus {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error.
        /// </summary>
        public static string DisplayName_VolumeStatus_AccessError {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled.
        /// </summary>
        public static string DisplayName_VolumeStatus_Controlled {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_Controlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed.
        /// </summary>
        public static string DisplayName_VolumeStatus_Destroyed {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string DisplayName_VolumeStatus_Offline {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relinquished.
        /// </summary>
        public static string DisplayName_VolumeStatus_Relinquished {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_Relinquished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncontrolled.
        /// </summary>
        public static string DisplayName_VolumeStatus_Uncontrolled {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_Uncontrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DisplayName_VolumeStatus_Unknown {
            get {
                return ResourceManager.GetString("DisplayName_VolumeStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline File must be selected..
        /// </summary>
        public static string ErrorMessage_BaselineRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_BaselineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Content Info must be selected.
        /// </summary>
        public static string ErrorMessage_BinaryPropertiesRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_BinaryPropertiesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular subdirectory hierarchy reference not allowed..
        /// </summary>
        public static string ErrorMessage_CircularReference {
            get {
                return ResourceManager.GetString("ErrorMessage_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlative File must be selected..
        /// </summary>
        public static string ErrorMessage_CorrelativeRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_CorrelativeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crawl operation has failed..
        /// </summary>
        public static string ErrorMessage_CrawlOperationFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_CrawlOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Created On&quot; date cannot be later than the &quot;Modified On&quot; date..
        /// </summary>
        public static string ErrorMessage_CreatedOnAfterModifiedOn {
            get {
                return ResourceManager.GetString("ErrorMessage_CreatedOnAfterModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name too long..
        /// </summary>
        public static string ErrorMessage_DisplayNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is required..
        /// </summary>
        public static string ErrorMessage_DisplayNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Type is invalid..
        /// </summary>
        public static string ErrorMessage_DriveTypeInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_DriveTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is already in use..
        /// </summary>
        public static string ErrorMessage_DuplicateDisplayName {
            get {
                return ResourceManager.GetString("ErrorMessage_DuplicateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate message with same error code..
        /// </summary>
        public static string ErrorMessage_DuplicateMessage {
            get {
                return ResourceManager.GetString("ErrorMessage_DuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use..
        /// </summary>
        public static string ErrorMessage_DuplicateName {
            get {
                return ResourceManager.GetString("ErrorMessage_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier already in use..
        /// </summary>
        public static string ErrorMessage_DuplicateVolumeIdentifier {
            get {
                return ResourceManager.GetString("ErrorMessage_DuplicateVolumeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be selected..
        /// </summary>
        public static string ErrorMessage_FileRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System is required..
        /// </summary>
        public static string ErrorMessage_FileSystemRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_FileSystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier too long..
        /// </summary>
        public static string ErrorMessage_IdentifierLength {
            get {
                return ResourceManager.GetString("ErrorMessage_IdentifierLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier is required..
        /// </summary>
        public static string ErrorMessage_IdentifierRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_IdentifierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Crawl Option is invalid..
        /// </summary>
        public static string ErrorMessage_InvalidDirectoryCrawlOption {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidDirectoryCrawlOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Crawl Option is invalid..
        /// </summary>
        public static string ErrorMessage_InvalidFileCrawlOption {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidFileCrawlOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not have the same content information as the target Redundancy Set..
        /// </summary>
        public static string ErrorMessage_InvalidFileInRedundantSet {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidFileInRedundantSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Length cannot be negative..
        /// </summary>
        public static string ErrorMessage_InvalidFileLength {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Redundancy Status is invalid..
        /// </summary>
        public static string ErrorMessage_InvalidFileRedundancyStatus {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidFileRedundancyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path validation error has occurred..
        /// </summary>
        public static string ErrorMessage_InvalidPathError {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Status is invalid..
        /// </summary>
        public static string ErrorMessage_InvalidVolumeStatus {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidVolumeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error has occurred..
        /// </summary>
        public static string ErrorMessage_IOError {
            get {
                return ResourceManager.GetString("ErrorMessage_IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;Last Hash Calulation Date&quot; cannot be later than the &quot;Modified On&quot; date..
        /// </summary>
        public static string ErrorMessage_LastHashCalculationAfterModifiedOn {
            get {
                return ResourceManager.GetString("ErrorMessage_LastHashCalculationAfterModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Last Hash Calulation Date&quot; cannot be earlier than the &quot;Created On&quot; date..
        /// </summary>
        public static string ErrorMessage_LastHashCalculationBeforeCreatedOn {
            get {
                return ResourceManager.GetString("ErrorMessage_LastHashCalculationBeforeCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Hash Calculation Date Required.
        /// </summary>
        public static string ErrorMessage_LastHashCalculationRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_LastHashCalculationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;Last Synchronized On&quot; date cannot be later than the &quot;Modified On&quot; date..
        /// </summary>
        public static string ErrorMessage_LastSynchronizedOnAfterModifiedOn {
            get {
                return ResourceManager.GetString("ErrorMessage_LastSynchronizedOnAfterModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Last Synchronized On&quot; date cannot be earlier than the &quot;Created On&quot; date..
        /// </summary>
        public static string ErrorMessage_LastSynchronizedOnBeforeCreatedOn {
            get {
                return ResourceManager.GetString("ErrorMessage_LastSynchronizedOnBeforeCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;LastSynchronizedOn&quot; date is required when &quot;Upstream Id&quot; is specified..
        /// </summary>
        public static string ErrorMessage_LastSynchronizedOnRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_LastSynchronizedOnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Name Length must be greater than zero..
        /// </summary>
        public static string ErrorMessage_MaxNameLengthInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxNameLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name too long..
        /// </summary>
        public static string ErrorMessage_NameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string ErrorMessage_NameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Subdirectory must be selected..
        /// </summary>
        public static string ErrorMessage_ParentRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_ParentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An excessive path length error has occurred..
        /// </summary>
        public static string ErrorMessage_PathTooLongError {
            get {
                return ResourceManager.GetString("ErrorMessage_PathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundancy Set must be selected..
        /// </summary>
        public static string ErrorMessage_RedundantSetRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_RedundantSetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference too long..
        /// </summary>
        public static string ErrorMessage_ReferenceLength {
            get {
                return ResourceManager.GetString("ErrorMessage_ReferenceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A security exception has occurred..
        /// </summary>
        public static string ErrorMessage_SecurityException {
            get {
                return ResourceManager.GetString("ErrorMessage_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An access authorization error has occurred..
        /// </summary>
        public static string ErrorMessage_UnauthorizedAccessError {
            get {
                return ResourceManager.GetString("ErrorMessage_UnauthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string ErrorMessage_UnexpectedError {
            get {
                return ResourceManager.GetString("ErrorMessage_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume and Parent Subdirectory cannot be selected at the same time..
        /// </summary>
        public static string ErrorMessage_VolumeAndParent {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeAndParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume already has another root directory specified..
        /// </summary>
        public static string ErrorMessage_VolumeHasRoot {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeHasRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name too long..
        /// </summary>
        public static string ErrorMessage_VolumeNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume or Parent Subdirectory must be selected..
        /// </summary>
        public static string ErrorMessage_VolumeOrParentRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeOrParentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot;
        ///           xmlns:ex=&quot;http://git.erwinefamily.net/FsInfoCat/V1/FsInfoCatExport.xsd&quot; targetNamespace=&quot;http://git.erwinefamily.net/FsInfoCat/V1/FsInfoCatExport.xsd&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://git.erwinefamily.net/FsInfoCat/V1/FsInfoCatExport.xsd&quot;&gt;
        ///    &lt;xs:simpleType name=&quot;UUID&quot;&gt;
        ///        &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///            &lt;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FsInfoCatExport {
            get {
                return ResourceManager.GetString("FsInfoCatExport", resourceCulture);
            }
        }
    }
}
