//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FilePathTestData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;./FilePathTestData.xsd&quot;&gt;
        ///    &lt;TestData InputString=&quot;file:///&quot;&gt;
        ///        &lt;Windows&gt;
        ///            &lt;AbsoluteUrl Match=&quot;file:///&quot; IsWellFormed=&quot;true&quot;&gt;
        ///                &lt;Authority&gt;
        ///                    &lt;Scheme Name=&quot;file&quot; Delimiter=&quot;://&quot; /&gt;
        ///                &lt;/Authority&gt;
        ///                &lt;Path Match=&quot;/&quot;&gt;
        ///                    &lt;Directory&gt;/&lt;/Directory&gt;
        ///                    &lt;FileName xsi:nil=&quot;true&quot; /&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilePathTestData {
            get {
                return ResourceManager.GetString("FilePathTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;FilePathTestData&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;unqualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;xs:simpleType name=&quot;HostType&quot;&gt;
        ///        &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///            &lt;xs:enumeration value=&quot;Unknown&quot; /&gt;
        ///            &lt;xs:enumeration value=&quot;DNS&quot; /&gt;
        ///            &lt;xs:enumeration value=&quot;IPV4&quot; /&gt;
        ///            &lt;xs:enumeration value=&quot;IPV6&quot; /&gt;
        ///        &lt;/xs:restriction&gt;
        ///    &lt;/xs:simpleType&gt;
        ///    &lt;xs:simple [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilePathTestDataSchema {
            get {
                return ResourceManager.GetString("FilePathTestDataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HostTestData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;./HostTestData.xsd&quot;&gt;
        ///    &lt;Host Name=&quot;&quot; IsIPV4=&quot;false&quot; IPV6=&quot;None&quot; IsDns=&quot;false&quot; HasOuterWS=&quot;false&quot; /&gt;
        ///    &lt;Host Name=&quot;.&quot; IsIPV4=&quot;false&quot; IPV6=&quot;None&quot; IsDns=&quot;false&quot; HasOuterWS=&quot;false&quot; /&gt;
        ///    &lt;Host Name=&quot;Y&quot; IsIPV4=&quot;false&quot; IPV6=&quot;None&quot; IsDns=&quot;true&quot; HasOuterWS=&quot;false&quot;&gt;Y&lt;/Host&gt;
        ///    &lt;Host Name=&quot;_&quot; IsIPV4=&quot;false&quot; IPV6=&quot;None&quot; IsDns=&quot;true&quot; HasOuterWS=&quot;false&quot;&gt;_&lt;/Host&gt;
        ///    &lt;Host Name=&quot;_OYuhCG&quot; IsIPV4=&quot;false&quot; IPV6=&quot;None [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HostTestData {
            get {
                return ResourceManager.GetString("HostTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;HostTestData&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;unqualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;xs:simpleType name=&quot;NZString&quot;&gt;
        ///        &lt;xs:restriction base=&quot;xs:normalizedString&quot;&gt;
        ///            &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///        &lt;/xs:restriction&gt;
        ///    &lt;/xs:simpleType&gt;
        ///    &lt;xs:simpleType name=&quot;IPV6Type&quot;&gt;
        ///        &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///            &lt;xs:enumeration value=&quot;None&quot; /&gt;
        ///            &lt;xs:enumerati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HostTestDataSchema {
            get {
                return ResourceManager.GetString("HostTestDataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UrlHelperTest xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;./UrlHelperTest.xsd&quot;&gt;
        ///    &lt;URI Value=&quot;&quot; Description=&quot;Empty String&quot;&gt;
        ///        &lt;Windows&gt;
        ///            &lt;FsPathRegex Success=&quot;true&quot;&gt;
        ///                &lt;Group Name=&quot;root&quot; Success=&quot;false&quot; /&gt;
        ///                &lt;Group Name=&quot;host&quot; Success=&quot;false&quot; /&gt;
        ///                &lt;Group Name=&quot;path&quot; Success=&quot;true&quot;&gt;&lt;/Group&gt;
        ///            &lt;/FsPathRegex&gt;
        ///            &lt;FormatGuess Success=&quot;false&quot; /&gt;
        ///            &lt;FileUriStrict Success=&quot;tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UrlHelperTest {
            get {
                return ResourceManager.GetString("UrlHelperTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;unqualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;xs:complexType name=&quot;CaptureType&quot;&gt;
        ///        &lt;xs:simpleContent&gt;
        ///            &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///                &lt;xs:attribute name=&quot;Success&quot; type=&quot;xs:boolean&quot; use=&quot;required&quot; /&gt;
        ///            &lt;/xs:extension&gt;
        ///        &lt;/xs:simpleContent&gt;
        ///    &lt;/xs:complexType&gt;
        ///    &lt;xs:complexType name=&quot;GroupType&quot;&gt;
        ///        &lt;xs:complexConte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UrlHelperTestSchema {
            get {
                return ResourceManager.GetString("UrlHelperTestSchema", resourceCulture);
            }
        }
    }
}
