//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Generator {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;?xml-model href="../../FsInfoCat.Generator/XmlSchemas/XmlSchema.xsd"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:import namespace="http://www.w3.org/XML/1998/namespace" /&gt;
        ///     &lt;xs:include schemaLocation="EnumDefinitions.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="InterfaceDefinitions.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="SqlStatements.xsd"/&gt;
        ///     &lt;xs:complexType name="BaseColumnDefinition"&gt;
        ///         &lt;xs:sequence&gt;
        ///             &lt;xs:element name=" [rest of string was truncated].
        /// </summary>
        public static string EntityTypesXsd {
            get {
                return ResourceManager.GetString("EntityTypes.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        /// &lt;xs:include schemaLocation="TypeNames.xsd"/&gt;
        /// &lt;xs:include schemaLocation="ExplicitNames.xsd"/&gt;
        /// &lt;xs:include schemaLocation="Documentation.xsd"/&gt;
        /// &lt;xs:group name="ConstructedInterfaces"&gt;
        ///     &lt;xs:choice&gt;
        ///         &lt;xs:choice&gt;
        ///             &lt;xs:element name="EntityInterface"&gt;
        ///                 &lt;xs:complexType&gt;
        ///                     &lt;xs:attribute name="Ref" type="InterfaceName" use="required" /&gt;
        ///                 &lt;/xs:c [rest of string was truncated].
        /// </summary>
        public static string ConstructedTypesXsd {
            get {
                return ResourceManager.GetString("ConstructedTypes.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:include schemaLocation="TypeNames.xsd"/&gt;
        ///     &lt;xs:complexType name="SeeAlsoDocumentation"&gt;
        ///         &lt;xs:attribute name="cref" type="xs:token" use="optional" /&gt;
        ///         &lt;xs:attribute name="href" type="xs:anyURI" use="optional" /&gt;
        ///     &lt;/xs:complexType&gt;
        ///     &lt;xs:complexType name="SeeDocumentation" mixed="true"&gt;
        ///         &lt;xs:attribute name="cref" type="xs:token" use="optional" /&gt;
        ///         &lt;xs:attribute nam [rest of string was truncated].
        /// </summary>
        public static string DocumentationXsd {
            get {
                return ResourceManager.GetString("Documentation.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:include schemaLocation="Documentation.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="TypeNames.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="ExplicitNames.xsd"/&gt;
        ///     &lt;xs:complexType name="EnumField"&gt;
        ///         &lt;xs:sequence&gt;
        ///             &lt;xs:element name="Documentation" type="BasicDefinitionDocumentation" /&gt;
        ///             &lt;xs:element name="Display" type="DisplayAttribute" /&gt;
        ///         &lt;/xs:sequence&gt;
        ///         &lt;xs:attribu [rest of string was truncated].
        /// </summary>
        public static string EnumDefinitionsXsd {
            get {
                return ResourceManager.GetString("EnumDefinitions.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:include schemaLocation="TypeNames.xsd"/&gt;
        ///     &lt;xs:simpleType name="ResourceNames"&gt;
        ///         &lt;xs:annotation&gt;
        ///             &lt;xs:documentation&gt;Any runtime or model type name that is not a generic type&lt;/xs:documentation&gt;
        ///         &lt;/xs:annotation&gt;
        ///         &lt;xs:restriction base="PublicMemberName"&gt;
        ///             &lt;xs:enumeration value="RedundancyUnconfirmed" /&gt;
        ///             &lt;xs:enumeration value="NotRedundant" /&gt;
        ///  [rest of string was truncated].
        /// </summary>
        public static string ExplicitNamesXsd {
            get {
                return ResourceManager.GetString("ExplicitNames.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:include schemaLocation="TypeNames.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="ConstructedTypes.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="ExplicitNames.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="Documentation.xsd"/&gt;
        ///     &lt;xs:complexType name="Property"&gt;
        ///         &lt;xs:sequence&gt;
        ///             &lt;xs:element name="Documentation" type="PropertyDocumentation" /&gt;
        ///             &lt;xs:element name="Display" type="DisplayAttribute [rest of string was truncated].
        /// </summary>
        public static string InterfaceDefinitionsXsd {
            get {
                return ResourceManager.GetString("InterfaceDefinitions.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:import namespace="http://www.w3.org/XML/1998/namespace" /&gt;
        ///     &lt;xs:include schemaLocation="EnumDefinitions.xsd"/&gt;
        ///     &lt;xs:include schemaLocation="InterfaceDefinitions.xsd"/&gt;
        ///     &lt;xs:complexType name="SqlCrawlStatusCompareType"&gt;
        ///         &lt;xs:attribute name="Entity" type="SimpleTypeName" use="optional" /&gt;
        ///         &lt;xs:attribute name="Column" type="SimpleTypeName" use="required" /&gt;
        ///         &lt;xs:attribute name="Value" type="CrawlStatusType" use [rest of string was truncated].
        /// </summary>
        public static string SqlStatementsXsd {
            get {
                return ResourceManager.GetString("SqlStatements.xsd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version="1.0" encoding="UTF-8"?&gt;
        /// &lt;xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
        ///     &lt;xs:simpleType name="AccessModifierType"&gt;
        ///         &lt;xs:restriction base="xs:NCName"&gt;
        ///             &lt;xs:enumeration value="Public" /&gt;
        ///             &lt;xs:enumeration value="Protected" /&gt;
        ///             &lt;xs:enumeration value="Internal" /&gt;
        ///             &lt;xs:enumeration value="ProtectedInternal" /&gt;
        ///             &lt;xs:enumeration value="Private" /&gt;
        ///         &lt;/xs:restriction&gt;
        ///     &lt;/xs:simpleType&gt;
        ///     &lt;xs:simpleType name= [rest of string was truncated].
        /// </summary>
        public static string TypeNamesXsd {
            get {
                return ResourceManager.GetString("TypeNames.xsd", resourceCulture);
            }
        }
    }
}
