//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.PS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.PS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the depth of recursion of items to import..
        /// </summary>
        internal static string Import_FileSystemInfo_Depth {
            get {
                return ResourceManager.GetString("Import_FileSystemInfo_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies an array of one or more string patterns to that match files to be excluded. Enter a path element or pattern, such as ` .txt` or `A `. Wildcard characters are accepted..
        /// </summary>
        internal static string Import_FileSystemInfo_Exclude {
            get {
                return ResourceManager.GetString("Import_FileSystemInfo_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a filter in the provider&apos;s format or language. The value of this parameter qualifies the Path parameter. The syntax of the filter, including the use of wildcards, depends on the provider. Filters are more efficient than other parameters, because the provider applies them when retrieving the objects, rather than having Windows PowerShell filter the objects after they are retrieved..
        /// </summary>
        internal static string Import_FileSystemInfo_Filter {
            get {
                return ResourceManager.GetString("Import_FileSystemInfo_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import hidden and system folders and files. By default, `Import-FileSystemInfo` doesn&apos;t import hidden or system files and folders..
        /// </summary>
        internal static string Import_FileSystemInfo_Force {
            get {
                return ResourceManager.GetString("Import_FileSystemInfo_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies, as a string array, a path to one or more locations. Unlike the Path parameter, the value of the LiteralPath parameter is used exactly as it is typed. No characters are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell PowerShell not to interpret any characters as escape sequences..
        /// </summary>
        internal static string Import_FileSystemInfo_LiteralPath {
            get {
                return ResourceManager.GetString("Import_FileSystemInfo_LiteralPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a path to one or more locations. Wildcards are permitted. The default location is the current directory (.)..
        /// </summary>
        internal static string Import_FileSystemInfo_Path {
            get {
                return ResourceManager.GetString("Import_FileSystemInfo_Path", resourceCulture);
            }
        }
    }
}
