namespace FsInfoCat.Generator
{
    public enum ElementNames
    {
        Models,
        Namespace,
        Class,
        Record,
        Struct,
        Interface,
        Enum,
        Field,
        Property,
        EventProperty,
        EventField,
        Documentation,
        BaseTypes,
        Delegate,
        Method,
        Constructor,
        Destructor,
        Operator,
        ConversionOperator,
        Unsupported,
        Type,
        DeclaringType,
        BaseType,
        Implements,
        Types
    }
}
