namespace FsInfoCat.Generator
{
    public enum XmlNames
    {
        EntityTypes,
        Enum,
        Name,
        Flags,
        Fields,
        Byte,
        SByte,
        Short,
        UShort,
        Int,
        UInt,
        Long,
        ULong,
        Documentation,
        Display,
        ShortName,
        Label,
        Description,
        Value,
        StatusMessageLevel,
        ErrorCode,
        MessageCode,
        Local,
        Upstream,
        data,
        name
    }
}
