//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Account1 = new HashSet<Account>();
            this.Account11 = new HashSet<Account>();
            this.HostDevices = new HashSet<HostDevice>();
            this.HostDevices1 = new HashSet<HostDevice>();
            this.UserCredentials = new HashSet<UserCredential>();
            this.UserCredentials1 = new HashSet<UserCredential>();
            this.Volumes = new HashSet<Volume>();
            this.Volumes1 = new HashSet<Volume>();
        }
    
        public System.Guid AccountID { get; set; }
        public string DisplayName { get; set; }
        public string LoginName { get; set; }
        public byte Role { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual ICollection<Account> Account11 { get; set; }
        public virtual Account Account3 { get; set; }
        public virtual ICollection<HostDevice> HostDevices { get; set; }
        public virtual ICollection<HostDevice> HostDevices1 { get; set; }
        public virtual ICollection<UserCredential> UserCredentials { get; set; }
        public virtual ICollection<UserCredential> UserCredentials1 { get; set; }
        public virtual ICollection<Volume> Volumes { get; set; }
        public virtual ICollection<Volume> Volumes1 { get; set; }
    }
}
