//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.CreatedBy_Account = new HashSet<Account>();
            this.Modified_Accounts = new HashSet<Account>();
            this.Created_HostDevices = new HashSet<HostDevice>();
            this.Modified_HostDevices = new HashSet<HostDevice>();
            this.Created_UserCredentials = new HashSet<UserCredential>();
            this.CreatedBy_UserCredentials = new HashSet<UserCredential>();
            this.Created_Volumes = new HashSet<Volume>();
            this.Modified_Volumes = new HashSet<Volume>();
        }
    
        public System.Guid AccountID { get; set; }
        public string DisplayName { get; set; }
        public string LoginName { get; set; }
        public byte Role { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual ICollection<Account> CreatedBy_Account { get; set; }
        public virtual Account Created_Accounts { get; set; }
        public virtual ICollection<Account> Modified_Accounts { get; set; }
        public virtual Account ModifiedBy_Account { get; set; }
        public virtual ICollection<HostDevice> Created_HostDevices { get; set; }
        public virtual ICollection<HostDevice> Modified_HostDevices { get; set; }
        public virtual ICollection<UserCredential> Created_UserCredentials { get; set; }
        public virtual ICollection<UserCredential> CreatedBy_UserCredentials { get; set; }
        public virtual ICollection<Volume> Created_Volumes { get; set; }
        public virtual ICollection<Volume> Modified_Volumes { get; set; }
    }
}
