//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model.Local
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDbContainer : DbContext
    {
        public LocalDbContainer()
            : base("name=LocalDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<FileSystem> FileSystems { get; set; }
        public virtual DbSet<FsSymbolicName> FsSymbolicNames { get; set; }
        public virtual DbSet<Directory> Directories { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<HashCalculation> HashCalculations { get; set; }
        public virtual DbSet<Redundancy> Redundancies { get; set; }
        public virtual DbSet<Comparison> Comparisons { get; set; }
    }
}
