//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model.Remote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volume()
        {
            this.Notes = "";
        }
    
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string VolumeName { get; set; }
        public string Identifier { get; set; }
        public Nullable<System.Guid> HostDeviceId { get; set; }
        public System.Guid FileSystemId { get; set; }
        public System.IO.DriveType Type { get; set; }
        public Nullable<bool> CaseSensitiveSearch { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public Nullable<long> MaxNameLength { get; set; }
        public string Notes { get; set; }
        public bool IsInactive { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual HostDevice HostDevice { get; set; }
        public virtual FileSystem FileSystem { get; set; }
        public virtual Directory RootDirectory { get; set; }
        public virtual UserProfile CreatedBy { get; set; }
        public virtual UserProfile ModifiedBy { get; set; }
    }
}
