//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-sensitive Search.
        /// </summary>
        public static string DisplayName_CaseSensitiveSearch {
            get {
                return ResourceManager.GetString("DisplayName_CaseSensitiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string DisplayName_CreatedOn {
            get {
                return ResourceManager.GetString("DisplayName_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName_DisplayName {
            get {
                return ResourceManager.GetString("DisplayName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        public static string DisplayName_FileSystem {
            get {
                return ResourceManager.GetString("DisplayName_FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier.
        /// </summary>
        public static string DisplayName_Identifier {
            get {
                return ResourceManager.GetString("DisplayName_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Synchronized On.
        /// </summary>
        public static string DisplayName_LastSynchronizedOn {
            get {
                return ResourceManager.GetString("DisplayName_LastSynchronizedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Name Length.
        /// </summary>
        public static string DisplayName_MaxNameLength {
            get {
                return ResourceManager.GetString("DisplayName_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string DisplayName_ModifiedOn {
            get {
                return ResourceManager.GetString("DisplayName_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        public static string DisplayName_ReadOnly {
            get {
                return ResourceManager.GetString("DisplayName_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string DisplayName_RootDirectory {
            get {
                return ResourceManager.GetString("DisplayName_RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote DB Identifier.
        /// </summary>
        public static string DisplayName_UpstreamId {
            get {
                return ResourceManager.GetString("DisplayName_UpstreamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name.
        /// </summary>
        public static string DisplayName_VolumeName {
            get {
                return ResourceManager.GetString("DisplayName_VolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name too long..
        /// </summary>
        public static string ErrorMessage_DisplayNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is required..
        /// </summary>
        public static string ErrorMessage_DisplayNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System is required..
        /// </summary>
        public static string ErrorMessage_FileSystemRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_FileSystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier too long..
        /// </summary>
        public static string ErrorMessage_IdentifierLength {
            get {
                return ResourceManager.GetString("ErrorMessage_IdentifierLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifier is required..
        /// </summary>
        public static string ErrorMessage_IdentifierRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_IdentifierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name too long..
        /// </summary>
        public static string ErrorMessage_NameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string ErrorMessage_NameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name too long..
        /// </summary>
        public static string ErrorMessage_VolumeNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name is required..
        /// </summary>
        public static string ErrorMessage_VolumeNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeNameRequired", resourceCulture);
            }
        }
    }
}
