//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasicLogin()
        {
            this.FailCount = 0;
            this.LockedOut = false;
            this.IsInactive = false;
        }
    
        public System.Guid Id { get; set; }
        public string LoginName { get; set; }
        public string PwHash { get; set; }
        public byte FailCount { get; set; }
        public bool LockedOut { get; set; }
        public bool IsInactive { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount CreatedBy { get; set; }
        public virtual UserAccount ModifiedBy { get; set; }
    }
}
