//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comparison
    {
        public System.Guid Id { get; set; }
        public System.Guid FileId1 { get; set; }
        public System.Guid FileId2 { get; set; }
        public bool AreEqual { get; set; }
    
        public virtual File File1 { get; set; }
        public virtual File File2 { get; set; }
    }
}
