//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbModel : DbContext
    {
        public DbModel()
            : base("name=DbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<HostDevice> HostDevices { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<DbUserRole> DbUserRoles { get; set; }
        public virtual DbSet<Subdirectory> Subdirectories { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Comparison> Comparisons { get; set; }
        public virtual DbSet<ChecksumCalculation> ChecksumCalculations { get; set; }
    
        public virtual ObjectResult<GetAutoUserAccountId_Result> GetAutoUserAccountId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAutoUserAccountId_Result>("GetAutoUserAccountId");
        }
    }
}
