//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModel : DbContext
    {
        public DbModel()
            : base("name=DbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<HostDevice> HostDevices { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<BasicLogin> BasicLogins { get; set; }
        public virtual DbSet<WindowsIdentityLogin> WindowsIdentityLogins { get; set; }
        public virtual DbSet<WindowsAuthDomain> WindowsAuthDomains { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<WindowsGroupIdentity> WindowsGroupIdentities { get; set; }
    }
}
