//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbUserRole
    {
        public string RoleName { get; set; }
        public string UserName { get; set; }
        public byte[] SID { get; set; }
        public int PrincipalId { get; set; }
    }
}
