//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public System.Guid GroupId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.Guid AddedById { get; set; }
    
        public virtual UserGroup Group { get; set; }
        public virtual UserAccount User { get; set; }
        public virtual UserAccount AddedBy { get; set; }
    }
}
