//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    
    [Flags]
    public enum HostPlatformType : byte
    {
        Unknown = 0,
        Windows = 1,
        Linux = 2,
        OSX = 3,
        XBox = 4
    }
}
