//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowsAuthDomain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WindowsAuthDomain()
        {
            this.IsInactive = false;
            this.AutoAddUsers = false;
            this.Logins = new HashSet<WindowsIdentityLogin>();
            this.Groups = new HashSet<WindowsGroupIdentity>();
        }
    
        public System.Guid Id { get; set; }
        public string SID { get; set; }
        public string Name { get; set; }
        public bool IsInactive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
        public string Notes { get; set; }
        public bool AutoAddUsers { get; set; }
        public Nullable<System.Guid> DefaultNewUserGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindowsIdentityLogin> Logins { get; set; }
        public virtual UserAccount CreatedBy { get; set; }
        public virtual UserAccount ModifiedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindowsGroupIdentity> Groups { get; set; }
        public virtual UserGroup DefaultNewUserGroup { get; set; }
    }
}
