//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsInfoCat.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsInfoCat.Model.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Equal.
        /// </summary>
        public static string DisplayName_AreEqual {
            get {
                return ResourceManager.GetString("DisplayName_AreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string DisplayName_AssignedTo {
            get {
                return ResourceManager.GetString("DisplayName_AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Group.
        /// </summary>
        public static string DisplayName_AssignmentGroup {
            get {
                return ResourceManager.GetString("DisplayName_AssignmentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-Sensitive Search.
        /// </summary>
        public static string DisplayName_CaseSensitiveSearch {
            get {
                return ResourceManager.GetString("DisplayName_CaseSensitiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string DisplayName_CreatedBy {
            get {
                return ResourceManager.GetString("DisplayName_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string DisplayName_CreatedOn {
            get {
                return ResourceManager.GetString("DisplayName_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Principal ID.
        /// </summary>
        public static string DisplayName_DbPrincipalId {
            get {
                return ResourceManager.GetString("DisplayName_DbPrincipalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Drive Type.
        /// </summary>
        public static string DisplayName_DefaultDriveType {
            get {
                return ResourceManager.GetString("DisplayName_DefaultDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default File Sytem Type.
        /// </summary>
        public static string DisplayName_DefaultFSType {
            get {
                return ResourceManager.GetString("DisplayName_DefaultFSType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Symbolic Name.
        /// </summary>
        public static string DisplayName_DefaultSymbolicName {
            get {
                return ResourceManager.GetString("DisplayName_DefaultSymbolicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Relocation Task.
        /// </summary>
        public static string DisplayName_DirectoryRelocationTask {
            get {
                return ResourceManager.GetString("DisplayName_DirectoryRelocationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName_DisplayName {
            get {
                return ResourceManager.GetString("DisplayName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Type.
        /// </summary>
        public static string DisplayName_DriveType {
            get {
                return ResourceManager.GetString("DisplayName_DriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File #1.
        /// </summary>
        public static string DisplayName_File1 {
            get {
                return ResourceManager.GetString("DisplayName_File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File #2.
        /// </summary>
        public static string DisplayName_File2 {
            get {
                return ResourceManager.GetString("DisplayName_File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Length.
        /// </summary>
        public static string DisplayName_FileLength {
            get {
                return ResourceManager.GetString("DisplayName_FileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Relocatoin Task.
        /// </summary>
        public static string DisplayName_FileRelocationTask {
            get {
                return ResourceManager.GetString("DisplayName_FileRelocationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Relocatoin Tasks.
        /// </summary>
        public static string DisplayName_FileRelocationTasks {
            get {
                return ResourceManager.GetString("DisplayName_FileRelocationTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        public static string DisplayName_FileSystem {
            get {
                return ResourceManager.GetString("DisplayName_FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System Default References.
        /// </summary>
        public static string DisplayName_FileSystemDefaults {
            get {
                return ResourceManager.GetString("DisplayName_FileSystemDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string DisplayName_FirstName {
            get {
                return ResourceManager.GetString("DisplayName_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Hash.
        /// </summary>
        public static string DisplayName_HashCalculation {
            get {
                return ResourceManager.GetString("DisplayName_HashCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Device.
        /// </summary>
        public static string DisplayName_HostDevice {
            get {
                return ResourceManager.GetString("DisplayName_HostDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Devices.
        /// </summary>
        public static string DisplayName_HostDevices {
            get {
                return ResourceManager.GetString("DisplayName_HostDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Platform Default References.
        /// </summary>
        public static string DisplayName_HostPlatformDefaults {
            get {
                return ResourceManager.GetString("DisplayName_HostPlatformDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Inactive.
        /// </summary>
        public static string DisplayName_IsInactive {
            get {
                return ResourceManager.GetString("DisplayName_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Accessed.
        /// </summary>
        public static string DisplayName_LastAccessed {
            get {
                return ResourceManager.GetString("DisplayName_LastAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Hash Calculation.
        /// </summary>
        public static string DisplayName_LastHashCalculation {
            get {
                return ResourceManager.GetString("DisplayName_LastHashCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string DisplayName_LastName {
            get {
                return ResourceManager.GetString("DisplayName_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Synchronized with Remote DB.
        /// </summary>
        public static string DisplayName_LastSynchronized {
            get {
                return ResourceManager.GetString("DisplayName_LastSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string DisplayName_LoginName {
            get {
                return ResourceManager.GetString("DisplayName_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Identifier.
        /// </summary>
        public static string DisplayName_MachineIdentifer {
            get {
                return ResourceManager.GetString("DisplayName_MachineIdentifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string DisplayName_MachineName {
            get {
                return ResourceManager.GetString("DisplayName_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Name Length.
        /// </summary>
        public static string DisplayName_MaxNameLength {
            get {
                return ResourceManager.GetString("DisplayName_MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Hash.
        /// </summary>
        public static string DisplayName_MD5Hash {
            get {
                return ResourceManager.GetString("DisplayName_MD5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string DisplayName_ModifiedBy {
            get {
                return ResourceManager.GetString("DisplayName_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string DisplayName_ModifiedOn {
            get {
                return ResourceManager.GetString("DisplayName_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Directory.
        /// </summary>
        public static string DisplayName_ParentDirectory {
            get {
                return ResourceManager.GetString("DisplayName_ParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        public static string DisplayName_ReadOnly {
            get {
                return ResourceManager.GetString("DisplayName_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundancy Set.
        /// </summary>
        public static string DisplayName_RedundancySet {
            get {
                return ResourceManager.GetString("DisplayName_RedundancySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string DisplayName_RootDirectory {
            get {
                return ResourceManager.GetString("DisplayName_RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string DisplayName_ShortDescription {
            get {
                return ResourceManager.GetString("DisplayName_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Identifier.
        /// </summary>
        public static string DisplayName_SID {
            get {
                return ResourceManager.GetString("DisplayName_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Directories.
        /// </summary>
        public static string DisplayName_SourceDirectories {
            get {
                return ResourceManager.GetString("DisplayName_SourceDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Files.
        /// </summary>
        public static string DisplayName_SourceFiles {
            get {
                return ResourceManager.GetString("DisplayName_SourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-directories.
        /// </summary>
        public static string DisplayName_SubDirectories {
            get {
                return ResourceManager.GetString("DisplayName_SubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Name.
        /// </summary>
        public static string DisplayName_SymbolicName {
            get {
                return ResourceManager.GetString("DisplayName_SymbolicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Directory.
        /// </summary>
        public static string DisplayName_TargetDirectory {
            get {
                return ResourceManager.GetString("DisplayName_TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Directory Relocation Tasks.
        /// </summary>
        public static string DisplayName_TargetDirectoryRelocationTasks {
            get {
                return ResourceManager.GetString("DisplayName_TargetDirectoryRelocationTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File.
        /// </summary>
        public static string DisplayName_TargetFile {
            get {
                return ResourceManager.GetString("DisplayName_TargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title/Rank.
        /// </summary>
        public static string DisplayName_Title {
            get {
                return ResourceManager.GetString("DisplayName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifer.
        /// </summary>
        public static string DisplayName_VolumeIdentifier {
            get {
                return ResourceManager.GetString("DisplayName_VolumeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name.
        /// </summary>
        public static string DisplayName_VolumeName {
            get {
                return ResourceManager.GetString("DisplayName_VolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Created By&quot; is not defined..
        /// </summary>
        public static string ErrorMessage_CreatedBy {
            get {
                return ResourceManager.GetString("ErrorMessage_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Symbolic Name must be selected..
        /// </summary>
        public static string ErrorMessage_DefaultSymbolicNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_DefaultSymbolicNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is too long..
        /// </summary>
        public static string ErrorMessage_DisplayNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is required..
        /// </summary>
        public static string ErrorMessage_DisplayNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File #1 must be selected..
        /// </summary>
        public static string ErrorMessage_File1Required {
            get {
                return ResourceManager.GetString("ErrorMessage_File1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File #2 must be selected..
        /// </summary>
        public static string ErrorMessage_File2Required {
            get {
                return ResourceManager.GetString("ErrorMessage_File2Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Length cannot be negative..
        /// </summary>
        public static string ErrorMessage_FileLengthNegative {
            get {
                return ResourceManager.GetString("ErrorMessage_FileLengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File must be selected..
        /// </summary>
        public static string ErrorMessage_FileRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System must be selected..
        /// </summary>
        public static string ErrorMessage_FileSystemRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_FileSystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name too long..
        /// </summary>
        public static string ErrorMessage_FirstNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Hash must be selected.
        /// </summary>
        public static string ErrorMessage_HashCalculationRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_HashCalculationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Device is required..
        /// </summary>
        public static string ErrorMessage_HostDeviceRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_HostDeviceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name too long..
        /// </summary>
        public static string ErrorMessage_LastNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required..
        /// </summary>
        public static string ErrorMessage_LastNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name is required..
        /// </summary>
        public static string ErrorMessage_LoginName {
            get {
                return ResourceManager.GetString("ErrorMessage_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name too long..
        /// </summary>
        public static string ErrorMessage_LoginNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_LoginNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Identifier is too long..
        /// </summary>
        public static string ErrorMessage_MachineIdentiferLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MachineIdentiferLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Identifier is required..
        /// </summary>
        public static string ErrorMessage_MachineIdentiferRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_MachineIdentiferRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name is too long..
        /// </summary>
        public static string ErrorMessage_MachineNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MachineNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name is required..
        /// </summary>
        public static string ErrorMessage_MachineNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_MachineNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Name Length cannot be negative..
        /// </summary>
        public static string ErrorMessage_MaxNameLengthNegative {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxNameLengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hash length.
        /// </summary>
        public static string ErrorMessage_MD5HashLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MD5HashLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Initial too long..
        /// </summary>
        public static string ErrorMessage_MILength {
            get {
                return ResourceManager.GetString("ErrorMessage_MILength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Modified By&quot; is not defined..
        /// </summary>
        public static string ErrorMessage_ModifiedBy {
            get {
                return ResourceManager.GetString("ErrorMessage_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date cannot be earlier than the creation date..
        /// </summary>
        public static string ErrorMessage_ModifiedOn {
            get {
                return ResourceManager.GetString("ErrorMessage_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name too long..
        /// </summary>
        public static string ErrorMessage_NameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string ErrorMessage_NameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Director or Volume must be selected..
        /// </summary>
        public static string ErrorMessage_NoParentOrVolume {
            get {
                return ResourceManager.GetString("ErrorMessage_NoParentOrVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Directory must be selected..
        /// </summary>
        public static string ErrorMessage_ParentDirectoryRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_ParentDirectoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform must be selected..
        /// </summary>
        public static string ErrorMessage_Platform {
            get {
                return ResourceManager.GetString("ErrorMessage_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundancy Set must be selected..
        /// </summary>
        public static string ErrorMessage_RedundancySetRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_RedundancySetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description is too long..
        /// </summary>
        public static string ErrorMessage_ShortDescriptionLength {
            get {
                return ResourceManager.GetString("ErrorMessage_ShortDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description is required..
        /// </summary>
        public static string ErrorMessage_ShortDescriptionRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_ShortDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Identifier required..
        /// </summary>
        public static string ErrorMessage_SID {
            get {
                return ResourceManager.GetString("ErrorMessage_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Identifier too long..
        /// </summary>
        public static string ErrorMessage_SIDLength {
            get {
                return ResourceManager.GetString("ErrorMessage_SIDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix too long..
        /// </summary>
        public static string ErrorMessage_SuffixLength {
            get {
                return ResourceManager.GetString("ErrorMessage_SuffixLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory must be selected..
        /// </summary>
        public static string ErrorMessage_TargetDirectory {
            get {
                return ResourceManager.GetString("ErrorMessage_TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title/Rank too long.
        /// </summary>
        public static string ErrorMessage_TitleLength {
            get {
                return ResourceManager.GetString("ErrorMessage_TitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifer is too long..
        /// </summary>
        public static string ErrorMessage_VolumeIdentiferLength {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeIdentiferLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Identifer is required..
        /// </summary>
        public static string ErrorMessage_VolumeIdentifierRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeIdentifierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name is too long..
        /// </summary>
        public static string ErrorMessage_VolumeNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Name is required..
        /// </summary>
        public static string ErrorMessage_VolumeNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessage_VolumeNameRequired", resourceCulture);
            }
        }
    }
}
